import type { StructuredReport } from "../types/report.js";

export function formatReportHtml(report: StructuredReport): string {
  const attendeeRows = (report.attendees || [])
    .map((a) => `<li>${esc(a.name)} — ${esc(a.title)}, ${esc(a.company)}</li>`)
    .join("\n    ");

  const productsHtml = (report.productsDiscussed || []).length > 0
    ? `<h3>Products Discussed</h3>
  <table border="1" cellpadding="4" cellspacing="0">
    <tr><th>Category</th><th>Details</th><th>Samples</th><th>Custom</th></tr>
    ${(report.productsDiscussed || [])
      .map(
        (p) =>
          `<tr><td>${esc(p.category)}</td><td>${esc(p.details)}</td><td>${esc(p.sampleStatus)}</td><td>${p.customFormulation ? "Yes" : "No"}</td></tr>`
      )
      .join("\n    ")}
  </table>`
    : "";

  const topics = (report.topicsDiscussed || [])
    .map((t) => `<li>${esc(t)}</li>`)
    .join("\n    ");

  const insights = (report.keyInsights || [])
    .map((i) => `<li>${esc(i)}</li>`)
    .join("\n    ");

  const actionRows = (report.actionItems || [])
    .map(
      (a) =>
        `<tr><td>${esc(a.action)}</td><td>${esc(a.owner)}</td><td>${a.dueDate || "TBD"}</td></tr>`
    )
    .join("\n    ");

  const nextStepsHtml = (report.nextSteps || [])
    .map((n) => `<li>${esc(n.step)} (${esc(n.timeline)})</li>`)
    .join("\n    ");

  const competitorHtml =
    report.competitorMentions && report.competitorMentions.length > 0
      ? `<h3>Competitor Intelligence</h3>
  <ul>
    ${report.competitorMentions
      .map((c) => `<li><strong>${esc(c.competitor)}:</strong> ${esc(c.context)}</li>`)
      .join("\n    ")}
  </ul>`
      : "";

  const decisionHtml = report.decisionProcess
    ? `<h3>Decision Process</h3>
  <ul>
    ${report.decisionProcess.decisionMaker ? `<li><strong>Decision Maker:</strong> ${esc(report.decisionProcess.decisionMaker)}</li>` : ""}
    ${report.decisionProcess.decisionTimeline ? `<li><strong>Timeline:</strong> ${esc(report.decisionProcess.decisionTimeline)}</li>` : ""}
    ${(report.decisionProcess.evaluationCriteria || []).length > 0 ? `<li><strong>Evaluation Criteria:</strong> ${(report.decisionProcess.evaluationCriteria).map(esc).join(", ")}</li>` : ""}
    ${(report.decisionProcess.otherStakeholders || []).length > 0 ? `<li><strong>Other Stakeholders:</strong> ${(report.decisionProcess.otherStakeholders).map(esc).join(", ")}</li>` : ""}
  </ul>`
    : "";

  const riskHtml = (report.riskFactors || []).length > 0
    ? `<h3>⚠ Risk Factors</h3>
  <ul>
    ${(report.riskFactors || []).map((r) => `<li>${esc(r)}</li>`).join("\n    ")}
  </ul>`
    : "";

  const pricingHtml = report.pricingNotes
    ? `<h3>Pricing Notes</h3><p>${esc(report.pricingNotes)}</p>`
    : "";

  const volumeHtml = report.volumeNotes
    ? `<h3>Volume Notes</h3><p>${esc(report.volumeNotes)}</p>`
    : "";

  const businessTypeLabel = report.businessType && report.businessType !== "not discussed"
    ? ` | <strong>Type:</strong> ${esc(report.businessType)}`
    : "";

  return `<h2>Sales Call Report</h2>
<p><strong>Date:</strong> ${esc(report.callDate)} | <strong>Type:</strong> ${esc(report.callType)} | <strong>Sentiment:</strong> ${esc(report.customerSentiment)}${businessTypeLabel}</p>

<h3>Attendees</h3>
<ul>
  ${attendeeRows}
</ul>

<h3>Summary</h3>
<p>${esc(report.summary)}</p>

${productsHtml}

<h3>Topics Discussed</h3>
<ul>
  ${topics}
</ul>

<h3>Key Insights</h3>
<ul>
  ${insights}
</ul>

<h3>Action Items</h3>
<table border="1" cellpadding="4" cellspacing="0">
  <tr><th>Action</th><th>Owner</th><th>Due Date</th></tr>
  ${actionRows}
</table>

<h3>Next Steps</h3>
<ul>
  ${nextStepsHtml}
</ul>

${competitorHtml}

${decisionHtml}

${riskHtml}

${pricingHtml}

${volumeHtml}

${report.dealStageRecommendation ? `<h3>Deal Stage Assessment</h3>
<p>Current: <strong>${esc(report.dealStageRecommendation.currentStage)}</strong> → Recommended: <strong>${esc(report.dealStageRecommendation.recommendedStage)}</strong></p>
<p><em>${esc(report.dealStageRecommendation.rationale)}</em></p>` : ""}

${report.followUpDate ? `<p><strong>Follow-up Date:</strong> ${esc(report.followUpDate)}</p>` : ""}

<hr>
<p style="color:#999;font-size:11px;">Generated by Westrock Voice Reporter | ${new Date().toISOString()} | AI-assisted</p>`;
}

export function formatReportPlainText(report: StructuredReport): string {
  const lines: string[] = [];

  lines.push(`SALES CALL REPORT — ${safe(report.callDate)} (${safe(report.callType)})`);
  if (report.businessType && report.businessType !== "not discussed") {
    lines.push(`Business Type: ${safe(report.businessType)}`);
  }
  lines.push("");
  lines.push("ATTENDEES:");
  for (const a of (report.attendees || [])) {
    lines.push(`  - ${safe(a.name)}, ${safe(a.title)} (${safe(a.company)})`);
  }
  lines.push("");
  lines.push("SUMMARY:");
  lines.push(`  ${safe(report.summary)}`);

  if ((report.productsDiscussed || []).length > 0) {
    lines.push("");
    lines.push("PRODUCTS DISCUSSED:");
    for (const p of report.productsDiscussed) {
      lines.push(`  - ${safe(p.category)}: ${safe(p.details)}`);
      lines.push(`    Samples: ${safe(p.sampleStatus)} | Custom Formulation: ${p.customFormulation ? "Yes" : "No"}`);
    }
  }

  lines.push("");
  lines.push("TOPICS DISCUSSED:");
  for (const t of (report.topicsDiscussed || [])) {
    lines.push(`  - ${safe(t)}`);
  }
  lines.push("");
  lines.push("KEY INSIGHTS:");
  for (const i of (report.keyInsights || [])) {
    lines.push(`  - ${safe(i)}`);
  }
  lines.push("");
  lines.push("ACTION ITEMS:");
  for (const a of (report.actionItems || [])) {
    lines.push(`  - ${safe(a.action)} (Owner: ${safe(a.owner)}, Due: ${a.dueDate || "TBD"})`);
  }
  lines.push("");
  lines.push("NEXT STEPS:");
  for (const n of (report.nextSteps || [])) {
    lines.push(`  - ${safe(n.step)} (${safe(n.timeline)})`);
  }

  if (report.competitorMentions && report.competitorMentions.length > 0) {
    lines.push("");
    lines.push("COMPETITOR INTEL:");
    for (const c of report.competitorMentions) {
      lines.push(`  - ${safe(c.competitor)}: ${safe(c.context)}`);
    }
  }

  if (report.decisionProcess) {
    lines.push("");
    lines.push("DECISION PROCESS:");
    if (report.decisionProcess.decisionMaker) {
      lines.push(`  Decision Maker: ${safe(report.decisionProcess.decisionMaker)}`);
    }
    if (report.decisionProcess.decisionTimeline) {
      lines.push(`  Timeline: ${safe(report.decisionProcess.decisionTimeline)}`);
    }
    if ((report.decisionProcess.evaluationCriteria || []).length > 0) {
      lines.push(`  Criteria: ${report.decisionProcess.evaluationCriteria.map(safe).join(", ")}`);
    }
    if ((report.decisionProcess.otherStakeholders || []).length > 0) {
      lines.push(`  Other Stakeholders: ${report.decisionProcess.otherStakeholders.map(safe).join(", ")}`);
    }
  }

  if ((report.riskFactors || []).length > 0) {
    lines.push("");
    lines.push("RISK FACTORS:");
    for (const r of report.riskFactors) {
      lines.push(`  ⚠ ${safe(r)}`);
    }
  }

  lines.push("");
  lines.push(`CUSTOMER SENTIMENT: ${safe(report.customerSentiment)}`);
  const dsr = report.dealStageRecommendation;
  if (dsr) {
    lines.push(`DEAL STAGE: ${safe(dsr.currentStage)} → ${safe(dsr.recommendedStage)}`);
    lines.push(`  Rationale: ${safe(dsr.rationale)}`);
  }

  if (report.pricingNotes) {
    lines.push("");
    lines.push(`PRICING: ${report.pricingNotes}`);
  }
  if (report.volumeNotes) {
    lines.push(`VOLUME: ${report.volumeNotes}`);
  }

  if (report.followUpDate) {
    lines.push(`FOLLOW-UP: ${report.followUpDate}`);
  }

  return lines.join("\n");
}

function esc(text: string | null | undefined): string {
  if (!text) return "";
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Safely convert any value to a string (guards against null/undefined from AI output) */
function safe(val: unknown): string {
  if (val == null) return "";
  return String(val);
}
